### ISSUE TITLE
Cloudrun link is broken

### ISSUE THREAD

**Issue by semiformal-net** [priyankavergadia/GCPSketchnote#7]
CloudRun image should link to `https://thecloudgirl.dev/run.html`

**Comment by priyankavergadia** [comment]
The link is working

**Comment by semiformal-net** [comment]
Are you certain? For me the link `https://thecloudgirl.dev/CloudRun.html` leads to a 404

**Comment by userravs** [comment]
Probably is this one: https://thecloudgirl.dev/run.html

![image](https://user-images.githubusercontent.com/1899902/139719304-d8b619ab-a1e0-4435-8b88-406fa59eb320.png)
